### ISSUE TITLE
Run into an problem when running BigBen locally with Docker

### ISSUE THREAD

**Issue by OUCHUNYU** [walmartlabs/bigben#31]
scripts provided in the project work mostly ok except when running the app I got 

```
bigben             | 2019-09-30 22:34:02.882 ERROR [main] BigBen:59 - error in loading modules, system will exit now
bigben             | com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))
bigben             | 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:232)
bigben             | 	at com.datastax.driver.cor`e.ControlConnection.connect(ControlConnection.java:79)
bigben             | 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1600)
bigben             | 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1518)
bigben             | 	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
bigben             | 	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
bigben             | 	at com.datastax.driver.core.Cluster.connect(Cluster.java:280)
bigben             | 	at com.walmartlabs.bigben.providers.domain.cassandra.CassandraModule.<clinit>(CassandraModule.kt:63)
bigben             | 	at java.lang.Class.forName0(Native Method)
bigben             | 	at java.lang.Class.forName(Class.java:264)
bigben             | 	at com.walmartlabs.bigben.utils.commons.ModuleRegistry.createModule(modules.kt:75)
bigben             | 	at com.walmartlabs.bigben.utils.commons.ModuleRegistry.loadModules(modules.kt:63)
bigben             | 	at com.walmartlabs.bigben.BigBen$Initializer.<clinit>(BigBen.kt:57)
bigben             | 	at com.walmartlabs.bigben.BigBen.init(BigBen.kt:42)
bigben             | 	at com.walmartlabs.bigben.app.App.<init>(app.kt:64)
bigben             | 	at com.walmartlabs.bigben.app.RunKt.app(run.kt:50)
bigben             | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
bigben             | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
bigben             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bigben             | 	at java.lang.reflect.Method.invoke(Method.java:498)
bigben             | 	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
bigben             | 	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:80)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:347)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:297)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:273)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:126)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
bigben             | 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
bigben             | 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:18)
bigben             | 	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:46)
bigben             | 	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:17)
bigben             | 	at com.walmartlabs.bigben.app.RunKt.main(run.kt:30)
bigben             | Exception in thread "main" java.lang.reflect.InvocationTargetException
bigben             | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
bigben             | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
bigben             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bigben             | 	at java.lang.reflect.Method.invoke(Method.java:498)
bigben             | 	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
bigben             | 	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:80)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
bigben             | 	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:347)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:297)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:273)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:126)
bigben             | 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
bigben             | 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
bigben             | 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:18)
bigben             | 	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:46)
bigben             | 	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:17)
bigben             | 	at com.walmartlabs.bigben.app.RunKt.main(run.kt:30)
bigben             | Caused by: java.lang.ExceptionInInitializerError
bigben             | 	at com.walmartlabs.bigben.BigBen$Initializer.<clinit>(BigBen.kt:61)
bigben             | 	at com.walmartlabs.bigben.BigBen.init(BigBen.kt:42)
bigben             | 	at com.walmartlabs.bigben.app.App.<init>(app.kt:64)
bigben             | 	at com.walmartlabs.bigben.app.RunKt.app(run.kt:50)
bigben             | 	... 19 more
bigben             | Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))
bigben             | 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:232)
bigben             | 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
bigben             | 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1600)
bigben             | 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1518)
bigben             | 	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
bigben             | 	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
bigben             | 	at com.datastax.driver.core.Cluster.connect(Cluster.java:280)
bigben             | 	at com.walmartlabs.bigben.providers.domain.cassandra.CassandraModule.<clinit>(CassandraModule.kt:63)
bigben             | 	at java.lang.Class.forName0(Native Method)
bigben             | 	at java.lang.Class.forName(Class.java:264)
bigben             | 	at com.walmartlabs.bigben.utils.commons.ModuleRegistry.createModule(modules.kt:75)
bigben             | 	at com.walmartlabs.bigben.utils.commons.ModuleRegistry.loadModules(modules.kt:63)
bigben             | 	at com.walmartlabs.bigben.BigBen$Initializer.<clinit>(BigBen.kt:57)
bigben             | 	... 22 more
```

So I switched to running it without docker. There might be something wrong in image as it was built many months ago.

**Comment by sandeepmalik** [comment]
Hi Chunyu, 

I will look into the docker image issue. Looks like Cassandra IP mapping is not correct. Were you able to run it without docker?

**Comment by OUCHUNYU** [comment]
Hi Sandeep,

Yes sir, I could run it without Docker, seems like the IP mapping issue.

Thanks for your help!

Chunyu
