### ISSUE TITLE
Unable to install BigBen:app version: 1.0.7-SNAPSHOT

### ISSUE THREAD

**Issue by nitiprabhu** [walmartlabs/bigben#38]
Hello, 

I tried installing Bigben ([bigben#non-docker-execution](https://github.com/walmartlabs/bigben#non-docker-execution)), but the execution is failing due to access.

Does it require any configuration setup? Here I have attached the log trace for the reference.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for BigBen:parent 1.0.7-SNAPSHOT:
[INFO] 
[INFO] BigBen:parent ...................................... SUCCESS [  0.287 s]
[INFO] BigBen:commons ..................................... SUCCESS [ 19.904 s]
[INFO] BigBen:lib ......................................... SUCCESS [ 10.523 s]
[INFO] Bigben:cron ........................................ SUCCESS [  3.245 s]
[INFO] BigBen:cassandra ................................... SUCCESS [  3.622 s]
[INFO] Bigben:kafka ....................................... SUCCESS [  2.409 s]
[INFO] BigBen:app ......................................... FAILURE [  2.051 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.303 s
[INFO] Finished at: 2020-01-20T12:25:17+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project bigben-app: Could not resolve dependencies for project com.walmartlabs.bigben:bigben-app:takari-jar:1.0.7-SNAPSHOT: Failed to collect dependencies at io.ktor:ktor-server-core:jar:1.1.1 -> org.jetbrains.kotlinx:atomicfu:jar:0.12.0: Failed to read artifact descriptor for org.jetbrains.kotlinx:atomicfu:jar:0.12.0: Could not transfer artifact org.jetbrains.kotlinx:atomicfu:pom:0.12.0 from/to jcenter (http://jcenter.bintray.com): **Access denied** to: http://jcenter.bintray.com/org/jetbrains/kotlinx/atomicfu/0.12.0/atomicfu-0.12.0.pom -> [Help 1]
[ERROR]_

**Comment by nitiprabhu** [comment]
Worked to me after I upgraded <ktor.version>**1.3.0**</ktor.version>

**Comment by sphirke** [comment]
In non-docker execution, I am getting below error while running app_run.sh 
`using JAVA_OPTS:
starting 1 app node(s)
starting node 1 at app port: 8080, hz port: 5701, logs: /root/bigben/build/exec/../configs/../../../bigben_logs/bigben_app_8080.log
tail: cannot open '/root/bigben/build/exec/../configs/../../../bigben_logs/bigben_app_8080.log' for reading: No such file or directory
tail: no files remaining
root@clm-aus-tlu6jc:~/bigben/build/exec# log4j:WARN Continuable parsing error 26 and column 77
log4j:WARN Attribute "xmlns:xsi" must be declared for element type "log4j:configuration".
log4j:WARN Continuable parsing error 26 and column 77
log4j:WARN Attribute "xsi:schemaLocation" must be declared for element type "log4j:configuration".
log4j:WARN Continuable parsing error 45 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
Exception in thread "main" java.lang.ClassNotFoundException: Module function cannot be found for the fully qualified name 'com.walmartlabs.bigben.app.RunKt.logs'
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:367)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:287)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:320)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:286)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:302)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:284)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
        at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
        at com.walmartlabs.bigben.app.RunKt.main(run.kt:30)
`

**Comment by aroysbox** [comment]
> Worked to me after I upgraded <ktor.version>**1.3.0**</ktor.version>. Current version is 1.1.1
> @sandeepmalik pls check whether it is a permanent fix, thanks

I think this access denied error is due to an update on jcenter side
January 13, 2020 | HTTP requests to JCenter will be denied. Only HTTPS will be supported.
Reference: https://jfrog.com/blog/secure-jcenter-with-https/

It worked for me once in pom.xml changed http://jcenter.bintray.com to https and build was successful for me
https://jcenter.bintray.com
